sonar.projectKey=Thierry-Heinz_DFSJS-Mettez-en-uvre-l-int-gration-et-le-d-ploiement-continu-d-une-application-full-stack-JavaScript
sonar.organization=thierry-heinz


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=DFSJS-Mettez-en-uvre-l-int-gration-et-le-d-ploiement-continu-d-une-application-full-stack-JavaScript
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8