input {
  http {
    port => 8080
    codec => "json"
    add_field => { "app_service" => "backend" }
  }

  syslog {
    port => 5140
    add_field => { "app_service" => "frontend" }
  }
}

output {
  if [app_service] == "backend" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "orion-logs-backend-%{+YYYY.MM.dd}"
    }
  } else if [app_service] == "frontend" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "orion-logs-frontend-%{+YYYY.MM.dd}"
    }
  }

}